# Generated by Django 6.0.7 on 2026-07-10 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('regions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('apartment', 'آپارتمان'), ('kalnagi', 'کلنگی'), ('land', 'زمین'), ('commercial', 'تجاری'), ('office', 'اداری'), ('villa', 'ویلا')], max_length=16)),
                ('address', models.TextField()),
                ('plak', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('vacant', 'خالی'), ('occupied', 'پر')], default='vacant', max_length=16)),
                ('occupancy_start', models.DateField(blank=True, null=True)),
                ('occupancy_end', models.DateField(blank=True, null=True)),
                ('is_for_sale', models.BooleanField(default=False)),
                ('price_per_meter', models.PositiveBigIntegerField(blank=True, null=True)),
                ('total_price', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_for_rent', models.BooleanField(default=False)),
                ('deposit', models.PositiveBigIntegerField(blank=True, null=True)),
                ('monthly_rent', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_for_rahn', models.BooleanField(default=False)),
                ('rahn_amount', models.PositiveBigIntegerField(blank=True, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=16)),
                ('beds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('cabinet_material', models.CharField(blank=True, default='', max_length=64)),
                ('build_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('has_storage', models.BooleanField(default=False)),
                ('storage_deed', models.BooleanField(default=False)),
                ('storage_area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('has_tobdil', models.BooleanField(default=False)),
                ('has_aqab_neshini', models.BooleanField(default=False)),
                ('aqab_neshini_desc', models.TextField(blank=True, default='')),
                ('taadad_bar', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gozar_kooche', models.CharField(blank=True, default='', max_length=64)),
                ('taadad_tabaghat', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('has_hayat', models.BooleanField(default=False)),
                ('hayat_area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_properties', to='people.person')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='regions.region')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rented_properties', to='people.person')),
            ],
            options={
                'verbose_name': 'ملک',
                'verbose_name_plural': 'ملک\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.CharField(max_length=512)),
                ('is_cover', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='properties.property')),
            ],
            options={
                'verbose_name': 'عکس ملک',
                'ordering': ['id'],
            },
        ),
    ]
