# Generated by Django 6.0.7 on 2026-07-10 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('properties', '0002_property_amenity_columns_media_fieldtype_fixes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_type', models.CharField(choices=[('owner', 'مالک'), ('tenant', 'مستأجر'), ('status', 'وضعیت'), ('price', 'قیمت'), ('other', 'سایر')], max_length=16)),
                ('field', models.CharField(max_length=64)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('manual', 'دستی'), ('contract', 'قرارداد')], max_length=16)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_history_entries', to='contracts.contract')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='properties.property')),
            ],
            options={
                'verbose_name': 'تاریخچه ملک',
                'ordering': ['-created_at'],
            },
        ),
    ]
