# Generated by Django 6.0.7 on 2026-07-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='occupancy_deposit',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='occupancy_monthly_rent',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='occupancy_rahn',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
