# Generated by Django 6.0.7 on 2026-07-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_occupancy_amount_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='title',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
    ]
