# Generated by Django 6.0.7 on 2026-07-10 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('rent_mortgage', 'اجاره/رهن'), ('buy', 'خرید')], max_length=16)),
                ('persons_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('beds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('needs', models.TextField(blank=True, default='')),
                ('preferred_floor', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_area', models.PositiveIntegerField(blank=True, null=True)),
                ('max_area', models.PositiveIntegerField(blank=True, null=True)),
                ('min_build_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_build_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_deposit', models.PositiveBigIntegerField(blank=True, null=True)),
                ('max_rent', models.PositiveBigIntegerField(blank=True, null=True)),
                ('budget', models.PositiveBigIntegerField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='people.person')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='regions.region')),
            ],
            options={
                'verbose_name': 'درخواست',
                'verbose_name_plural': 'درخواست\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
