# Generated by Django 6.0.7 on 2026-07-10 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_history'),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='matched_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_requests', to='properties.property'),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('open', 'باز'), ('done', 'انجام\u200cشده')], default='open', max_length=8),
        ),
        migrations.AddField(
            model_name='request',
            name='target_property_type',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='units_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='wants_elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='wants_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='wants_storage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('rent', 'اجاره'), ('rahn', 'رهن'), ('sale', 'فروش')], max_length=8),
        ),
    ]
