# Generated by Django 6.0.7 on 2026-07-10 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_type', models.CharField(choices=[('sale', 'فروش'), ('rent', 'اجاره'), ('rahn', 'رهن کامل')], max_length=8)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('sale_price', models.PositiveBigIntegerField(blank=True, null=True)),
                ('deposit_amount', models.PositiveBigIntegerField(blank=True, null=True)),
                ('monthly_rent', models.PositiveBigIntegerField(blank=True, null=True)),
                ('rahn_amount', models.PositiveBigIntegerField(blank=True, null=True)),
                ('contract_image', models.CharField(blank=True, default='', max_length=512)),
                ('notes', models.TextField(blank=True, default='')),
                ('party_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts_as_party_a', to='people.person')),
                ('party_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts_as_party_b', to='people.person')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='properties.property')),
            ],
            options={
                'verbose_name': 'قرارداد',
                'verbose_name_plural': 'قراردادها',
                'ordering': ['-created_at'],
            },
        ),
    ]
